import type { RequirementAnnotation } from '@/components/requirementAnnotations';

export const portalOperationLogAnnotations: RequirementAnnotation[] = [
  {
    noteId: 'POL-1',
    number: '1',
    page: '操作日志',
    module: '入口与权限',
    target: '个人中心 / 操作日志入口与页面标题',
    ruleLabel: '业务数据与权限来源',
    ruleItems: [
      { text: '入口权限来源于门户当前登录成员的租户角色；仅租户管理员展示「个人中心 / 操作日志」。' },
      { text: '查询范围由服务端按当前登录租户强制限定，不接受前端传入其他租户作为查询依据；日志不可编辑或手动删除。' },
    ],
    stateLabel: '状态与异常',
    stateItems: [
      { text: '租户管理员有权限时展示页面；普通成员无入口，接口直接访问也必须拒绝。' },
      { text: '租户身份失效或无权限时，不展示旧日志或其他租户内容，并给出明确权限提示。' },
    ],
    recoveryLabel: '恢复方式',
    recoveryItems: [
      { text: '成员切换到有效租户或管理员权限恢复后，重新进入页面再发起查询；无权限时不提供绕过入口。' },
    ],
    acceptance: '分别以租户管理员、普通成员和失效租户身份验收；只有管理员可进入，页面、接口与导出均不能越租户。',
    topTab: '个人中心',
    menuKey: '操作日志',
  },
  {
    noteId: 'POL-2',
    number: '2',
    page: '操作日志',
    module: '来源 Tab 与记录范围',
    target: '门户操作 / API / MCP Tab',
    ruleLabel: '业务数据来源',
    ruleItems: [
      { text: '门户操作来源于登录成员实际发到服务端的业务动作；API、MCP 来源于可归属到当前租户及凭证绑定成员的服务端审计记录。' },
      { text: '三类来源都记录成功与失败；用户取消、仅前端校验未发请求、字段无实际变化不生成日志。' },
      { text: '进入页面、查看详情、搜索、筛选、切换 Tab 等浏览行为，以及系统定时任务、自动重试、自动推送等无法归属到成员或其凭证的自动行为不展示。' },
    ],
    stateLabel: '状态与异常',
    stateItems: [
      { text: '切换 Tab 后使用该来源的查询结果；API、MCP 凭证被撤销或成员被删除后，历史日志仍保留操作发生时的成员与凭证名称、标识快照。' },
      { text: '来源无法归属时不进入任一 Tab，且不得误归属到其他成员或凭证。' },
    ],
    recoveryLabel: '恢复方式',
    recoveryItems: [
      { text: 'Tab 查询失败时保留当前 Tab，显示失败状态和「重新加载」；恢复后仅重查当前来源。' },
    ],
    acceptance: '分别触发三类成功、失败操作并核对归属；验证浏览、未发请求的校验失败及系统自动行为不出现在任一 Tab。',
    topTab: '个人中心',
    menuKey: '操作日志',
  },
  {
    noteId: 'POL-3',
    number: '3',
    page: '操作日志',
    module: '筛选与时间',
    target: '日志筛选区',
    ruleLabel: '业务数据来源',
    ruleItems: [
      { text: '时间范围的数据来源是服务端审计记录的操作发生时间；操作者来自日志保存的门户登录成员或凭证绑定成员快照，功能模块和操作类型来自服务端审计分类。' },
      { text: '三个 Tab 共用时间范围、操作者、功能模块、操作类型；API、MCP 额外按日志保存的凭证名称快照筛选。' },
      { text: '默认查近 7 天，单次查询时间跨度最长 90 天；操作内容和操作结果仅展示，不作为筛选条件。' },
    ],
    stateLabel: '状态与异常',
    stateItems: [
      { text: '筛选条件同时生效，变更任一条件后从第一页展示；当前 Tab 无匹配记录时显示对应空状态。' },
      { text: '时间跨度超过 90 天时阻止查询并提示缩短时间范围，不展示不符合条件的旧结果。' },
    ],
    recoveryLabel: '恢复方式',
    recoveryItems: [
      { text: '超限后缩短至 90 天以内重新查询；查询失败时保留筛选条件并通过「重新加载」恢复。' },
    ],
    acceptance: '验证默认近 7 天、90 天内边界及超限拦截；公共筛选组合正确，且凭证筛选只出现在 API、MCP Tab。',
    topTab: '个人中心',
    menuKey: '操作日志',
  },
  {
    noteId: 'POL-4',
    number: '4',
    page: '操作日志',
    module: '列表与结果',
    target: '操作日志列表',
    ruleLabel: '业务数据来源',
    ruleItems: [
      { text: '列表数据来源于服务端审计记录，公共字段为操作时间、操作者、功能模块、操作类型、操作内容、操作结果、IP 地址；API、MCP 额外展示凭证名称快照。' },
      { text: '默认按操作时间倒序并支持分页；操作结果统一为成功、失败，以文字状态标签区分。' },
    ],
    stateLabel: '状态与异常',
    stateItems: [
      { text: '无数据时根据当前 Tab 和筛选条件显示空状态；查询失败时不展示旧数据或虚构内容，改为显示失败状态。' },
      { text: '日志保留 180 天，到期由系统自动清理；前台不提供删除或修改操作。' },
    ],
    recoveryLabel: '恢复方式',
    recoveryItems: [
      { text: '查询失败状态提供「重新加载」，重试使用当前 Tab、时间和筛选条件；其他已加载功能不因此误报失败。' },
    ],
    acceptance: '核对三个 Tab 字段差异、时间倒序、跨页分页和成功/失败标签；分别覆盖有数据、无数据及查询失败后重试。',
    topTab: '个人中心',
    menuKey: '操作日志',
  },
  {
    noteId: 'POL-5',
    number: '5',
    page: '操作日志',
    module: '详情与脱敏',
    target: '操作详情抽屉',
    ruleLabel: '业务数据来源',
    ruleItems: [
      { text: '详情来源于所选服务端审计记录；展示列表基础信息，API、MCP 展示操作发生时保存的凭证名称快照。' },
      { text: '失败操作展示服务端记录的可读失败原因；编辑类操作只展示实际变化字段及脱敏后的变更前、变更后值。' },
      { text: '请求信息按已有安全规则脱敏；Token、API Key、密码、Cookie、密钥和完整敏感参数不写入日志且不展示。' },
    ],
    stateLabel: '状态与异常',
    stateItems: [
      { text: '成功、失败详情均展示对应结果；不存在实际变化的编辑请求不应有日志或伪造变更前后值。' },
      { text: '详情数据缺失时显示「详情暂不可用」，不影响关闭抽屉或继续使用列表。' },
    ],
    recoveryLabel: '恢复方式',
    recoveryItems: [
      { text: '详情缺失时返回列表后可再次打开同一条记录；持续缺失由服务端按日志标识排查，不改用未脱敏原始参数。' },
    ],
    acceptance: '分别验收成功、失败、编辑变更、凭证已撤销和详情缺失；页面不得出现 Token、API Key、密码、Cookie、密钥或完整敏感参数。',
    topTab: '个人中心',
    menuKey: '操作日志',
    openEvent: 'portal-operation-log:open-detail',
  },
  {
    noteId: 'POL-6',
    number: '6',
    page: '操作日志',
    module: '导出与留痕',
    target: '导出按钮',
    ruleLabel: '业务数据来源',
    ruleItems: [
      { text: '导出数据来源于服务端按当前登录租户、当前 Tab、时间范围和页面筛选条件重新查得的审计记录；不跨租户、不默认导出其他 Tab。' },
      { text: '导出字段沿用页面脱敏规则，不包含 Token、API Key、密码、Cookie、密钥和完整敏感参数。' },
      { text: '发起导出本身作为一条门户操作由服务端留痕，导出成功和失败均记录实际结果。' },
    ],
    stateLabel: '状态与异常',
    stateItems: [
      { text: '导出中防止重复提交；成功后下载当前筛选结果，失败时展示可读失败原因且不伪造成功文件。' },
      { text: '页面筛选结果为空时，导出结果也必须与当前空集一致，不回退到全量数据。' },
    ],
    recoveryLabel: '恢复方式',
    recoveryItems: [
      { text: '导出失败后保留当前 Tab 和筛选条件，用户可按原条件重试；每次失败请求仍按实际结果生成门户操作日志。' },
    ],
    acceptance: '组合不同 Tab、时间和筛选条件验证导出与当前结果一致，且仅含本租户脱敏数据；导出成功、失败及重试均可查到自身留痕。',
    topTab: '个人中心',
    menuKey: '操作日志',
  },
];
