import type { RequirementAnnotation } from '@/components/requirementAnnotations';

export const businessCustomParameterAnnotations: RequirementAnnotation[] = [
  {
    noteId: 'BCP-1.1',
    number: '1.1',
    page: '后台-数据源管理',
    module: '数据源列表与行业产品筛选',
    target: '数据源管理列表顶部',
    rule: '行业产品筛选改为 rounded tabs，并作为数据源列表的主筛选入口。',
    ruleItems: [
      { text: '默认选中“电商取数宝”，不提供“全部”tab。' },
      { text: '切换行业产品后刷新数据源列表，并重置平台类型、平台名称等从属筛选。' },
      { text: '“更新流程包”和“添加”位于同一行右侧，仍保留原有批量更新流程包能力。' },
    ],
    state: '当前 tab、数据源列表、筛选项和分页状态需要保持一致。',
    acceptance: '打开后台管理 > 数据源管理时默认看到电商取数宝；切换 tab 后列表与筛选联动，右侧操作按钮位置不变。',
    topTab: '后台管理',
    menuKey: '数据源管理',
  },
  {
    noteId: 'BCP-1.3',
    number: '1.2',
    page: '后台-数据源管理',
    module: '采集时间类型',
    target: '基础信息 > 采集时间类型 / 运行时间设置',
    rule: '采集时间类型决定前台市场详情里的“支持取数时间条件”。',
    ruleItems: [
      { text: '可选类型为日、周、月、实时；后台勾选几个，前台就展示几个。' },
      { text: '日、周、月勾选后自动展开运行时间设置，分别维护平台出数时间和建议启动时间。' },
      { text: '实时不展开运行时间设置，也不展示动态时间范围设置。' },
    ],
    exception: '如果某个时间类型没有配置建议启动时间，前台只展示时间类型名称，不展示“建议取数时间”。',
    acceptance: '保存日/周/月/实时组合后，市场详情展示相同类型；配置建议启动时间后展示“建议取数时间：xx:xx”。',
    topTab: '后台管理',
    menuKey: '数据源管理',
    openEvent: 'business-custom:open-connector-basic',
  },
  {
    noteId: 'BCP-1.4',
    number: '1.3',
    page: '后台-数据源管理',
    module: '流程配置',
    target: '流程配置 > 业务参数类型与表头 schema',
    rule: '后台只定义数据源需要哪类业务参数和表头名称，真实参数集内容由前台用户在新建计划或参数管理中维护。',
    ruleItems: [
      { text: '业务参数类型仅支持本店商品配置、行业类目配置、竞品店铺配置、竞品商品配置、竞品品牌配置。' },
      { text: '五类默认表头分别为：商品 ID；一级/二级/三级类目；竞店名称/一级类目；一级类目/商品 ID/所属店铺；竞品名称/一级/二级/三级类目。' },
      { text: '本店商品配置固定一列表头，不允许新增多列。' },
      { text: '行业类目配置新增列默认四级类目、五级类目并持续递增；竞品店铺配置从二级类目开始递增；竞品品牌配置从四级类目开始递增；竞品商品配置新增列默认“请命名”。' },
      { text: '表头可点击编辑，“添加”只新增表头列，不新增真实参数数据行。' },
      { text: '切换业务参数类型时重置为该类型默认表头，避免旧字段残留。' },
    ],
    state: '“支持按业务拆分心跳”只保存数据源执行拆分策略，默认关闭；开启后执行侧按业务参数明细拆分心跳。',
    acceptance: '保存数据源后，新建计划的参数弹窗和参数管理新增/编辑页能按同一表头 schema 渲染字段。',
    topTab: '后台管理',
    menuKey: '数据源管理',
    openEvent: 'business-custom:open-connector-flow',
  },
  {
    noteId: 'BCP-1.5',
    number: '1.4',
    page: '后台-数据源管理',
    module: '自定义配置与 info',
    target: '流程配置 > 自定义配置',
    rule: '自定义配置 JSON 是前台自定义参数和说明文案的来源。',
    ruleItems: [
      { text: '普通自定义参数在前台读取 desc 值作为字段名称和说明，不再另写一套解释。' },
      { text: '当 paramDataColumns 中存在 start_ty_unit 和 end_ty_unit，前台映射为“动态时间范围”。' },
      { text: '如果后台未写 info 或没有具体值，前台不展示空说明或占位提示。' },
    ],
    exception: '实时计划不需要动态时间范围，即使历史配置中存在开始/结束推移字段，实时计划也不展示该设置。',
    acceptance: '市场详情和新建计划读取同一份自定义配置；开始/结束推移时长在前台显示为动态时间范围。',
    topTab: '后台管理',
    menuKey: '数据源管理',
    openEvent: 'business-custom:open-connector-flow',
  },
  {
    noteId: 'BCP-2.1',
    number: '2.1',
    page: '前台-市场详情',
    module: '数据源详情',
    target: '数据源市场 > 数据源详情头部',
    rule: '市场详情用于让用户理解数据源用途、数据来源和创建计划入口。',
    ruleItems: [
      { text: '数据来源读取后台数据源管理中的采集路径字段。' },
      { text: '使用说明入口读取后台数据源维护的使用说明 URL。' },
      { text: '点击“立即使用”进入前台新建计划，并携带当前数据源上下文。' },
    ],
    exception: '没有使用说明 URL 时提示暂无文档，不跳转空页面。',
    acceptance: '从市场详情点击立即使用后，打开新建计划并自动带入当前数据源、平台和数据周期。',
    topTab: '数据源市场',
    menuKey: '数据源市场',
    openEvent: 'business-custom:open-market-detail',
  },
  {
    noteId: 'BCP-2.2',
    number: '2.2',
    page: '前台-市场详情',
    module: '能力概述',
    target: '市场详情 > 功能概述',
    rule: '功能概述展示用户创建计划前必须理解的参数和时间条件。',
    ruleItems: [
      { text: '支持查询条件来源于业务参数类型和自定义参数；业务参数展示后台配置的业务参数名称，自定义参数读取 desc。' },
      { text: 'start_ty_unit、end_ty_unit 在前端特殊映射为“动态时间范围”。' },
      { text: '支持取数时间条件来源于后台采集时间类型，日/周/月/实时按后台勾选结果展示。' },
      { text: '如果后台设置了运行时间，追加“建议取数时间：xx:xx”；未设置则不展示建议时间。' },
    ],
    acceptance: '市场详情能说明该数据源需要哪些业务参数、自定义参数以及支持哪些取数时间类型。',
    topTab: '数据源市场',
    menuKey: '数据源市场',
    openEvent: 'business-custom:open-market-detail',
  },
  {
    noteId: 'BCP-3.1',
    number: '3.1',
    page: '前台-新建计划',
    module: '数据源配置',
    target: '新建计划 > 数据源配置列表',
    rule: '用户选择数据源后，系统需要判断是否存在必填业务参数配置。',
    ruleItems: [
      { text: '数据源缺少参数集时展示明确提示，并在数据源行上标记异常状态。' },
      { text: '点击编辑进入参数弹窗；用户必须选择已有参数集或新增参数集。' },
      { text: '不支持临时参数，所有新增或编辑结果必须沉淀到对应业务参数类型的参数管理中。' },
    ],
    exception: '未补齐必填业务参数时不允许进入下一步或创建计划。',
    acceptance: '缺少参数集的数据源会阻断下一步；补齐后保留当前计划上下文并允许继续。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'task-plan:open-plan-drawer',
  },
  {
    noteId: 'BCP-3.2',
    number: '3.2',
    page: '前台-新建计划',
    module: '参数集选择',
    target: '编辑参数 > 参数集下拉',
    rule: '参数集下拉只展示参数集名称，避免在列表项内堆叠兼容状态、副文本或说明。',
    ruleItems: [
      { text: 'hover 参数集名称时展示参数集明细 Popover，内容为表格。' },
      { text: '表格最多展示 3 行，超出后垂直滚动并保持表头固定。' },
      { text: 'Popover 不允许遮挡编辑、删除等操作按钮。' },
      { text: '下拉底部提供“新增参数”入口，按当前数据源业务参数类型打开新增弹窗。' },
    ],
    acceptance: '用户能在不离开新建计划的情况下预览参数集明细，并能新增、编辑或删除参数集。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'business-custom:open-plan-param-editor',
  },
  {
    noteId: 'BCP-3.3',
    number: '3.3',
    page: '前台-新建计划',
    module: '自定义参数编辑',
    target: '编辑参数 > 高级设置 / 动态时间范围',
    rule: '动态时间范围只在后台自定义配置存在 start_ty_unit、end_ty_unit 且当前不是实时计划时展示。',
    ruleItems: [
      { text: '高级设置默认收起，展开后展示动态时间范围设置。' },
      { text: '文案为“每次取 x 天前至 y 天前的数据”。' },
      { text: '如果后台写了 info 且有具体值，在字段旁展示说明入口；没有值不展示。' },
    ],
    exception: '实时计划不展示动态时间范围，也不保留历史动态时间范围快照。',
    acceptance: '日/周/月计划可配置动态时间范围；实时计划进入编辑参数弹窗时该区域不出现。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'business-custom:open-plan-param-editor',
  },
  {
    noteId: 'BCP-3.4',
    number: '3.4',
    page: '前台-新建计划',
    module: '新增参数集',
    target: '新增业务参数弹窗',
    rule: '新增参数集弹窗按当前数据源业务参数类型和后台表头 schema 动态渲染。',
    ruleItems: [
      { text: '用户只能编辑参数集名称、备注和表格内容，不能修改表头。' },
      { text: '表格内容沿用已有新增行、导入、导出入口；本期要求这些入口按当前数据源 schema 校验。' },
      { text: '开启“设为默认参数配置”后，后续选择该数据源时自动带入此参数集。' },
      { text: '若该数据源已绑定其他默认参数集，保存前二次提示是否更换默认。' },
      { text: '保存并使用后新增参数集沉淀到对应参数管理，并自动回填当前数据源。' },
    ],
    exception: '保存或导入校验失败时不覆盖当前配置；空行或必填列缺失时在单元格内展示错误，不使用全局 toast 代替。',
    acceptance: '新增本店商品、行业类目、竞品店铺、竞品商品、竞品品牌参数时字段分别匹配后台 schema。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'business-custom:open-plan-param-create',
  },
  {
    noteId: 'BCP-3.5',
    number: '3.5',
    page: '前台-新建计划',
    module: '计划提交校验',
    target: '新建计划 > 下一步 / 确定',
    rule: '业务参数是计划创建必填项，缺失时不允许创建计划。',
    ruleItems: [
      { text: '点击下一步时检查所有已选数据源是否满足业务参数要求。' },
      { text: '失败时提示具体数据源业务参数不能为空，并停留在当前配置页。' },
      { text: '用户修正参数后，已选择的平台、店铺、数据源和计划配置上下文不清空。' },
    ],
    acceptance: '未选择或未新增参数集时无法进入执行信息；补齐后可继续提交。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'task-plan:open-plan-drawer',
  },
  {
    noteId: 'BCP-4.1',
    number: '4.1',
    page: '前台-参数管理',
    module: '参数集列表',
    target: '参数管理 > 关联数据源列',
    rule: '参数管理用于维护真实参数集内容，并展示参数集与数据源的关联关系。',
    ruleItems: [
      { text: '新增“关联数据源”列；一个参数集允许关联多个数据源。' },
      { text: '关联数据源为空时显示“-”；多个数据源按名称展示。' },
    ],
    state: '删除参数集不影响历史计划快照；如果该参数集是某数据源默认参数集，删除后同步清空该数据源默认关系。',
    acceptance: '列表能看到参数集关联了哪些数据源；关联数据源为空显示“-”；删除默认参数集后再次选择该数据源不会自动带入已删除参数集。',
    topTab: '电商取数宝',
    menuKey: '本店商品配置',
  },
  {
    noteId: 'BCP-4.2',
    number: '4.2',
    page: '前台-参数管理',
    module: '参数集新增/编辑',
    target: '参数管理 > 新增/编辑参数集抽屉',
    rule: '参数集新增/编辑页按关联数据源读取后台 schema，并维护真实参数明细。',
    ruleItems: [
      { text: '关联数据源放在表单最上方，且必填；一个参数集可关联多个数据源。' },
      { text: '选择或变更关联数据源后，根据数据源 schema 动态更新表格列。' },
      { text: '多个关联数据源必须业务参数类型一致、表头 schema 一致；不一致时不允许保存，用户需拆分为不同参数集。' },
      { text: '保存时校验参数集名称、关联数据源和每个必填单元格。' },
    ],
    exception: '移除关联数据源时，同步清空该数据源与当前参数集之间的默认关系。',
    acceptance: '保存后列表更新参数集名称和关联数据源；后续新建计划可选择该参数集。',
    topTab: '电商取数宝',
    menuKey: '本店商品配置',
    openEvent: 'business-custom:open-param-drawer',
  },
];
