import type { RequirementAnnotation } from '@/components/requirementAnnotations';

export const autoRetryAnnotations: RequirementAnnotation[] = [
  {
    noteId: 'AR-1.1',
    number: '1.1',
    page: '计划管理',
    module: '重试列表字段',
    target: '计划管理列表 > 重试',
    rule: '重试是计划属性。列表只展示未开启或已开启，并支持按开启状态筛选。',
    exception: '历史计划默认未开启；不继承旧的产品线级自动重试配置。',
    state: '复制计划同步复制重试开关、执行时段和机器人配置。',
    acceptance: '列表、筛选、编辑回显和计划详情四处状态一致。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
  },
  {
    noteId: 'AR-2.1',
    number: '2.1',
    page: '新建/编辑计划',
    module: '重试总开关',
    target: '高级设置 > 自动重试设置',
    rule: '用户只决定是否允许自动重试。运维平台回传修复完成后，系统仅在开关开启时生成一次重试。',
    exception: '关闭只影响后续修复事件，不改写历史运行记录。',
    state: '新建计划默认关闭，编辑计划按当前配置回显；功能提示在开关开启和关闭时始终可见。',
    acceptance: '新建和编辑均可保存、关闭并正确回显，提示文案与开关状态无关。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'task-plan:open-plan-drawer',
  },
  {
    noteId: 'AR-2.2',
    number: '2.2',
    page: '新建/编辑计划',
    module: '重试时段与云资源',
    target: '高级设置 > 重试执行时段 / 重试云资源',
    rule: '运维修复事件生成的重试只在配置时段内排队执行；支持使用计划执行机器人或指定机器人。',
    exception: '正常计划优先；资源忙时继续等待，窗口结束后顺延到下一个重试窗口。',
    state: '指定机器人时必须选择可用机器人；使用计划执行机器人时不再重复选择。',
    acceptance: '执行时段、机器人模式、指定机器人显隐和必填校验均可保存并回显。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
    openEvent: 'task-plan:open-plan-drawer',
  },
  {
    noteId: 'AR-3.1',
    number: '3.1',
    page: '计划详情',
    module: '重试详情',
    target: '计划详情 > 重试策略',
    rule: '只读展示开启状态、重试执行时段和重试云资源。',
    exception: '未开启时显示“未开启重试”，不展示空字段。',
    state: '展示计划当前配置，不覆盖历史运行记录中的配置快照。',
    acceptance: '详情与列表摘要、编辑回显一致。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
  },
  {
    noteId: 'AR-4.1',
    number: '4.1',
    page: '计划管理',
    module: '计划生命周期',
    target: '计划管理列表 > 更多',
    rule: '复制计划同步复制重试配置；关闭计划后不再生成新重试；删除前处理排队或运行中的重试任务。',
    exception: '指定机器人复制后需重新校验可用性；历史运行和工单关联不可删除。',
    state: '关闭或删除不覆盖历史重试快照。',
    acceptance: '复制、关闭、删除对配置、队列和历史的影响可分别验证。',
    topTab: '电商取数宝',
    menuKey: '计划管理',
  },
];
