import type { RequirementAnnotation } from '@/components/requirementAnnotations';

const dateStatusPreviewItems = [
  { text: '成功', previews: [{ type: 'tag' as const, color: 'green', icon: 'success' as const, label: '成功' }] },
  { text: '异常', previews: [{ type: 'tag' as const, color: 'orange', icon: 'remind' as const, label: '异常' }] },
  { text: '失败', previews: [{ type: 'tag' as const, color: 'red', icon: 'failed' as const, label: '失败' }] },
  { text: '等待', previews: [{ type: 'tag' as const, color: 'arcoblue', icon: 'waiting' as const, label: '等待' }] },
  { text: '无任务', previews: [{ type: 'tag' as const, color: 'gray', label: '无任务' }] },
];

export const etlDataMonitoringAnnotations: RequirementAnnotation[] = [
  {
    noteId: 'ETL-1.1',
    number: '1.1',
    page: '监控视图列表',
    module: '卡片配色',
    target: '监控视图卡片',
    rule: '卡片顶部装饰色由黄色渐变调整为取数宝主蓝色。',
    ruleItems: [
      { text: '只调整卡片装饰色，不改变卡片内容、打开视图和关闭页签逻辑。' },
    ],
    acceptance: '监控视图列表不再出现黄色渐变卡片。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-view-list',
  },
  {
    noteId: 'ETL-2.1',
    number: '2.1',
    page: '店铺维度视图',
    module: '列表字段',
    target: '店铺维度前五列表头',
    rule: '店铺维度前五列调整为平台类型、子平台、店铺名称、动态取数时间范围、关联任务。',
    ruleItems: [
      { text: '店铺名称固定在第三列。' },
      { text: '动态取数时间范围固定在第四列，展示当前日期状态列覆盖的最早日期至最晚日期。' },
      { text: '自定义列为原有能力，本期不改造；店铺名称、关联任务仍不可隐藏。' },
    ],
    acceptance: '前五列顺序正确，动态取数时间范围与当前日期列范围一致。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-2.2',
    number: '2.2',
    page: '店铺维度视图',
    module: '刷新位置',
    target: '店铺维度刷新按钮',
    rule: '刷新按钮移动到状态筛选左侧，保持纯图标按钮样式。',
    acceptance: '刷新按钮位于状态筛选左侧，点击后刷新当前监控数据。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-2.3',
    number: '2.3',
    page: '店铺维度视图',
    module: '状态与下钻',
    target: '店铺维度日期状态单元格',
    rule: '日期状态表示数据交付最终结果，并按统一优先级聚合。',
    ruleLabel: '前端样式',
    ruleItems: dateStatusPreviewItems,
    exceptionLabel: '展示规则',
    exceptionItems: [
      { text: '实际任务按“失败 > 异常 > 等待 > 成功”聚合；只要存在实际任务就忽略无任务。' },
      { text: '全部明细均无实际任务时，整体才显示无任务。' },
      { text: '失败：取数阶段 2xxx/3xxx，或任一入库错误；异常：取数阶段 1xxx，或入库成功后表校验不通过。' },
      { text: '原因不在列表列内展示，只在状态 hover 时展示。' },
      { text: '同一天存在多个失败或异常时，原因按 1、2、3 编号换行。' },
      { text: '行 hover 时展示 icon + “下钻”文本按钮；非 hover 时仅展示状态 Tag。' },
    ],
    acceptance: '状态样式与页面一致；点击状态或下钻入口后进入对应店铺、对应业务日期的明细页。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-3.1',
    number: '3.1',
    page: '数据表维度视图',
    module: '状态说明浮层',
    target: '状态说明按钮',
    rule: '状态说明浮层从按钮下方展开，避免被页面顶部裁切。',
    ruleItems: [
      { text: '内容展示失败、异常、等待、成功、无任务五种聚合状态及判定说明。' },
    ],
    acceptance: '浮层内容完整可见，不被页面顶部或容器边界截断。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-table-view',
  },
  {
    noteId: 'ETL-3.3',
    number: '3.3',
    page: '数据表维度视图',
    module: '状态与下钻',
    target: '数据表维度日期状态单元格',
    rule: '日期状态表示数据交付最终结果，并按统一优先级聚合。',
    ruleLabel: '前端样式',
    ruleItems: dateStatusPreviewItems,
    exceptionLabel: '展示规则',
    exceptionItems: [
      { text: '实际任务按“失败 > 异常 > 等待 > 成功”聚合；只要存在实际任务就忽略无任务。' },
      { text: '全部明细均无实际任务时，整体才显示无任务。' },
      { text: '失败：取数阶段 2xxx/3xxx，或任一入库错误；异常：取数阶段 1xxx，或入库成功后表校验不通过。' },
      { text: '原因不在列表列内展示，只在状态 hover 时展示。' },
      { text: '同一天存在多个店铺失败或异常时，原因按 1、2、3 编号换行。' },
      { text: '行 hover 时展示 icon + “下钻”文本按钮；非 hover 时仅展示状态 Tag。' },
    ],
    acceptance: '状态样式与页面一致；点击状态或下钻入口后进入对应数据表、对应业务日期的明细页。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-table-view',
  },
  {
    noteId: 'ETL-4.2',
    number: '4.2',
    page: '下钻明细页',
    module: '明细表字段',
    target: '下钻明细表格列',
    rule: '下钻明细表展示任务级字段，字段文案以本期确认口径为准。',
    ruleItems: [
      { text: '明细表只展示取数执行、数据入库、数据校验三段链路状态，不展示最终状态。' },
      { text: '错误码和失败/异常原因不单独占列，hover 具体失败或异常状态时展示。' },
      { text: '问题阶段由状态所在列明确；同值错误码仍需按取数或入库阶段分别解释。' },
    ],
    acceptance: '失败或异常状态可 hover 查看错误码和原因；明细表无最终状态、问题阶段、错误码和原因独立列。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-detail',
  },
];
