import type { RequirementAnnotation } from '@/components/requirementAnnotations';

export const etlDataMonitoringAnnotations: RequirementAnnotation[] = [
  {
    noteId: 'ETL-1.2', number: '1.2', page: '监控视图列表', module: '视图页签样式', target: '监控视图页签栏',
    rule: '由线框页签调整为紧凑圆角页签，当前项以浅色底和蓝色文字突出；不可关闭页签与可关闭页签之间使用 12px 高竖线分组。',
    ruleLabel: 'Before / After', ruleItems: [{ text: '线上旧页签与当前可操作页签', example: 'view-tabs' }],
    acceptance: '当前项清晰；“监控视图列表”与可关闭视图之间显示 12px 高竖线；可切换及关闭已打开视图，“监控视图列表”不可关闭。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-2.1',
    number: '2.1',
    page: '店铺维度视图',
    module: '列表字段',
    target: '店铺维度前四列表头',
    locateMode: 'column-headers',
    rule: '店铺维度前四列调整为平台类型、子平台、店铺名称、关联计划。',
    ruleLabel: 'Before / After',
    ruleItems: [
      { text: '列表字段对照（宽表可横向滚动）', example: 'store-columns' },
    ],
    acceptance: '前四列顺序正确；不展示动态取数时间范围列，列设置中也不提供该列。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-2.2',
    number: '2.2',
    page: '店铺维度视图',
    module: '新增主动刷新按钮',
    target: '店铺维度刷新按钮',
    rule: '新增主动刷新按钮，位于状态筛选右侧。',
    ruleLabel: 'Before / After',
    ruleItems: [{ text: '工具栏对照', example: 'store-refresh' }],
    acceptance: '刷新按钮位于状态筛选右侧；点击后刷新当前监控数据并保留筛选条件。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-2.3',
    number: '2.3',
    page: '店铺维度视图',
    module: '状态与下钻',
    target: '店铺维度日期状态单元格',
    rule: '日期状态表示数据交付最终结果，并按统一优先级聚合。',
    ruleLabel: 'Before / After',
    ruleItems: [{ text: '日期状态样式与判定规则对照', example: 'store-status' }],
    exceptionLabel: '展示规则',
    exceptionItems: [
      { text: '实际任务按“失败 > 异常 > 等待 > 成功”聚合；只要存在实际任务就忽略无任务。' },
      { text: '失败：取数阶段 2xxx/3xxx、任一入库错误，或超过所属计划的运行超时时间。异常：取数阶段 1xxx，或入库成功后表校验不通过；同时超时时按失败优先。' },
      { text: '每个计划使用本次执行实际生效的分钟阈值；严格超过才失败。阈值缺失不补默认值，历史记录不按新阈值重算。超时只改变监控归类，不终止执行或自动重试。' },
    ],
    acceptance: '失败悬浮显示全部编号原因；行悬浮显示下钻入口；无任务不可下钻；其余状态进入对应店铺、业务日期的明细页。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-2.4', number: '2.4', page: '店铺维度视图', module: '日期与计划搜索', target: '店铺视图筛选区',
    rule: '时间范围置于平台 / 子平台左侧；组合搜索增加计划名称，筛选关联计划列。',
    ruleLabel: '前端交互',
    ruleItems: [
      { text: '计划搜索、组合筛选与无结果恢复', example: 'store-filters' },
      { text: '日期含起止两端，同时限制日期列和状态匹配；清空恢复可用日期。所有条件同时满足才展示，任一条件变化回第一页。' },
      { text: '搜索默认店铺名称，可切换计划名称；计划名称匹配该行关联计划中的任一名称，忽略首尾空格。切换字段保留关键词，清空关键词不清空其他条件。' },
    ],
    acceptance: '日期位于最左，计划搜索结果与关联计划列一致，状态仅在所选日期内匹配；无结果及清空恢复正确。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-view',
  },
  {
    noteId: 'ETL-3.1',
    number: '3.1',
    page: '店铺 / 数据表维度视图',
    module: '状态说明浮层',
    target: '状态说明按钮',
    rule: '状态说明浮层从按钮下方展开并对齐右边缘；保证长文案换行，不被顶部、右侧或容器边界裁切。',
    ruleLabel: 'Before / After',
    ruleItems: [
      { text: '旧版实拍与新版完整浮层', example: 'status-help' },
    ],
    acceptance: '浮层内容完整可见，不被页面顶部或容器边界截断。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-table-view',
  },
  {
    noteId: 'ETL-3.3',
    number: '3.3',
    page: '数据表维度视图',
    module: '状态与下钻',
    target: '数据表维度日期状态单元格',
    rule: '日期状态表示数据交付最终结果，并按统一优先级聚合。',
    ruleLabel: '前端交互',
    ruleItems: [{ text: '数据表状态、原因与下钻交互', example: 'table-status' }],
    exceptionLabel: '数据表聚合',
    exceptionItems: [
      { text: '按所选数据表下各店铺的实际任务聚合；公共状态优先级和计划超时判定与店铺维度一致。' },
      { text: '多个原因按店铺逐项展示；超时只改变汇总状态，三段原始状态保持不变。' },
    ],
    acceptance: '失败悬浮显示全部编号原因；行悬浮显示下钻入口；无任务不可下钻；其余状态进入对应数据表、业务日期的明细页。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-table-view',
  },
  {
    noteId: 'ETL-3.4', number: '3.4', page: '数据表维度视图', module: '计划名称搜索', target: '数据表视图筛选区',
    rule: '表名称组合搜索增加计划名称，匹配关联计划列；日期、数据源及状态筛选同时生效。',
    ruleLabel: '前端交互',
    ruleItems: [
      { text: '计划搜索、组合筛选与无结果恢复', example: 'table-filters' },
      { text: '默认表名称，匹配中文或英文表名；切换计划名称后，匹配该行任一关联计划名称。关键词忽略首尾空格，切换字段保留关键词，清空仅解除关键词限制。' },
      { text: '日期含起止两端，同时限制日期列与状态匹配范围；清空恢复可用日期。条件变更回到第一页。' },
    ],
    acceptance: '计划名称查询结果与关联计划列一致；与数据源、日期及状态组合生效，清空不误清其他条件。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-table-view',
  },
  {
    noteId: 'ETL-4.2',
    number: '4.2',
    page: '下钻明细页',
    module: '店铺下钻明细字段',
    target: '店铺下钻明细表',
    rule: '固定选中店铺和业务日期，查看该店铺各报表、任务的交付情况；字段规则仅作用于店铺下钻。',
    ruleItems: [
      { text: '直接查看并操作店铺下钻 Before / After', example: 'store-detail' },
      { text: '行内数据日期取执行明细的实际起止日期；顶部日期仅是下钻条件。无任务展示空态。' },
      { text: '重试后的父子状态同步见 ETL-4.9。' },
    ],
    acceptance: '定位进入所选店铺和业务日期的完整明细表；报表可不同，明细均属于所选店铺。不跳到数据表明细。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-detail',
  },
  {
    noteId: 'ETL-4.3',
    number: '4.3',
    page: '下钻明细页',
    module: '数据表下钻明细字段',
    target: '数据表下钻明细表',
    rule: '固定选中数据表和业务日期，查看该表各店铺、任务的交付情况；字段规则仅作用于数据表下钻。',
    ruleItems: [
      { text: '直接查看并操作数据表下钻 Before / After', example: 'table-detail' },
      { text: '行内数据日期取执行明细的实际起止日期；顶部日期仅是下钻条件。每行是一条店铺执行明细，无任务展示空态。' },
      { text: '同一报表、同一实际数据日期范围的相邻明细，平台类型、子平台、数据日期、数据周期、报表中英文名、数据源按各列相同值合并。店铺、关联计划、存储、三段状态、耗时、时间及操作仍逐行展示。' },
      { text: '先筛选、再分页，最后重新计算当前页内合并；不同报表或实际日期不合并，不跨页合并。列隐藏与排序不改变合并分组和原始明细条数。' },
      { text: '重试后的父子状态同步见 ETL-4.9。' },
    ],
    acceptance: '定位进入所选数据表和业务日期的完整明细表；店铺可不同，明细均属于所选表。不跳到店铺明细。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-table-detail',
  },
  {
    noteId: 'ETL-4.4', number: '4.4', page: '下钻明细页', module: '明细搜索与状态筛选', target: '下钻明细搜索及状态筛选区',
    rule: '本期在两种下钻页增加组合搜索与分阶段状态筛选。多个筛选条件同时满足才展示；只筛选当前下钻范围。',
    ruleLabel: 'Before / After',
    ruleItems: [
      { text: '旧版搜索入口与新版组合筛选，可直接切换阶段体验', example: 'detail-filters' },
      { text: '关键词支持任务名、店铺名、数据源名、表名；表名匹配中文或英文。默认任务名，关键词为空时不限制。关键词和状态变更后回到第一页。' },
      { text: '默认取数执行，未选状态时不限制。切换阶段清空已选状态；清空状态不清空关键词。搜索字段切换保留关键词。' },
      { text: '页面文案映射：待运行 → 等待，运行失败 → 失败，已完成 → 成功；原始状态值保留。行内状态与筛选采用同一映射。校验正常、无需校验及无数据归入成功，校验不通过显示失败；汇总日期仍可显示异常，两者层级不同。' },
      { text: '无匹配结果显示空态，可清空关键词或状态恢复。' },
    ],
    acceptance: '三段各自只出现规定选项；按原始别名记录也能筛中。切换阶段、清空和关键词组合均正确，结果分页重置。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-detail',
  },
  {
    noteId: 'ETL-4.5', number: '4.5', page: '下钻明细页', module: '返回与标题样式', target: '下钻返回入口及标题日期',
    rule: '返回箭头补充“返回”文案，店铺或数据表名称后以蓝色日期标签展示当前下钻日期。',
    ruleLabel: 'Before / After', ruleItems: [{ text: '旧版文本日期与新版日期标签', example: 'detail-heading' }],
    acceptance: '返回当前所属监控视图；名称长时省略且可查看完整名称。日期来自所点业务日期格，不替代行内实际取数范围。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-detail',
  },
  {
    noteId: 'ETL-4.6', number: '4.6', page: '下钻明细页', module: '列显示与排序', target: '下钻列设置入口',
    rule: '本期将下钻列设置改为可勾选、可拖拽的浮层，仅作用于当前下钻表格；店铺与数据表下钻共用交互，各自使用其字段清单。',
    ruleLabel: 'Before / After', ruleItems: [
      { text: '旧版入口与新版可操作列设置', example: 'detail-column-settings' },
      { text: '平台类型、子平台、数据日期、操作不可隐藏；操作不可拖动且固定最右。隐藏再显示保留当前排序。' },
      { text: '恢复默认同时恢复全部列和默认顺序；退出当前下钻后恢复默认。' },
    ],
    acceptance: '拖拽后表头顺序同步，必显列不能取消，操作列始终最右；恢复默认有效，不影响查询条件和数据。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-detail',
  },
  {
    noteId: 'ETL-4.7', number: '4.7', page: '下钻明细页', module: '表格内容左对齐', target: '下钻操作列表头', locateMode: 'column-headers',
    rule: '汇总视图与两种下钻的表头、单元格内容统一左对齐；操作列固定最右。',
    ruleItems: [{ text: 'After · 代表字段、状态和操作左对齐', example: 'detail-actions' }],
    acceptance: '文本、状态 Tag、info、无数据及不同数量的操作按钮均从单元格左侧起排。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-detail',
  },
  {
    noteId: 'ETL-4.8', number: '4.8', page: '下钻明细页', module: '字段命名与隐藏', target: '下钻改名字段表头', locateMode: 'column-headers',
    rule: '两种下钻页统一前端字段命名，并隐藏执行结果；不改数据来源、原始字段及后端计算。',
    ruleLabel: 'Before / After', ruleItems: [
      { text: '字段改名前后及隐藏范围', example: 'detail-field-names' },
    ],
    acceptance: '表头、列设置与预览命名一致；执行结果及其列设置项均不可见，三段链路状态仍展示。',
    topTab: '电商取数宝', menuKey: '数据监控', openEvent: 'etl-monitor:open-store-detail',
  },
  {
    noteId: 'ETL-4.9',
    number: '4.9',
    page: '下钻明细页',
    module: '重试后父子状态同步',
    target: '下钻明细重试入口',
    rule: '两种下钻共用最新有效执行：重试受理后更新当前行三段状态，父表用同一结果重新聚合；旧尝试仅在日志中保留。',
    ruleItems: [{
      text: '可操作状态演示',
      example: 'retry-consistency',
    }],
    acceptance: '等待、成功、再次失败和提交失败时父子状态符合完整流程，且不新增明细行。',
    topTab: '电商取数宝',
    menuKey: '数据监控',
    openEvent: 'etl-monitor:open-store-detail',
  },
];
